"""Load the deterministic demo fixtures into PostGIS.

The fixture datasets are synthetic. They exist to exercise the spatial join, the
scorer, and the optimizer without depending on a network fetch, and every row
they create is tagged `DEMO_FIXTURE` so it can never be mistaken for an official
snapshot.

    uv run --project apps/api python scripts/load_fixtures.py
    uv run --project apps/api python scripts/load_fixtures.py --reset
"""

from __future__ import annotations

import argparse
import asyncio
import json

import _bootstrap  # noqa: F401  (sys.path side effect)
from _bootstrap import FIXTURES_DIR

from app.db.session import dispose_engine, session_scope
from app.domain.runtime_mode import RuntimeMode
from app.services import snapshots
from sqlalchemy import text

BUS_STOPS_FIXTURE = FIXTURES_DIR / "bus_stops_demo.geojson"
SVI_FIXTURE = FIXTURES_DIR / "svi_tracts_demo.geojson"

FIXTURE_LICENSE_NOTE = (
    "Synthetic fixture data generated by scripts/generate_fixtures.py. "
    "Not derived from any official dataset and not redistributable as one."
)

_UPSERT_STOP = text(
    """
    INSERT INTO bus_stops (stop_id, location_name, shelter_count, ridership_value, geom, source_snapshot_id)
    VALUES (
        :stop_id, :location_name, :shelter_count, :ridership_value,
        ST_SetSRID(ST_MakePoint(:longitude, :latitude), 4326), :snapshot_id
    )
    ON CONFLICT (stop_id) DO UPDATE SET
        location_name = EXCLUDED.location_name,
        shelter_count = EXCLUDED.shelter_count,
        ridership_value = EXCLUDED.ridership_value,
        geom = EXCLUDED.geom,
        source_snapshot_id = EXCLUDED.source_snapshot_id
    """
)

_UPSERT_TRACT = text(
    """
    INSERT INTO svi_tracts (geoid, overall_percentile, geom, source_snapshot_id)
    VALUES (
        :geoid, :overall_percentile,
        ST_Multi(ST_SetSRID(ST_GeomFromGeoJSON(CAST(:geometry AS text)), 4326)),
        :snapshot_id
    )
    ON CONFLICT (geoid) DO UPDATE SET
        overall_percentile = EXCLUDED.overall_percentile,
        geom = EXCLUDED.geom,
        source_snapshot_id = EXCLUDED.source_snapshot_id
    """
)


def _read(path):
    if not path.is_file():
        raise SystemExit(f"Missing fixture {path}. Run scripts/generate_fixtures.py first.")
    raw = path.read_bytes()
    return json.loads(raw.decode("utf-8")), snapshots.checksum_of(raw)


async def load(reset: bool) -> None:
    stops_doc, stops_checksum = _read(BUS_STOPS_FIXTURE)
    tracts_doc, tracts_checksum = _read(SVI_FIXTURE)

    async with session_scope() as session:
        if reset:
            # Fixture reset must never touch live records, so it is scoped to
            # rows that belong to fixture snapshots.
            await session.execute(
                text(
                    """
                    DELETE FROM bus_stops WHERE source_snapshot_id IN (
                        SELECT id FROM source_snapshots WHERE evidence_mode = 'DEMO_FIXTURE'
                    )
                    """
                )
            )
            await session.execute(
                text(
                    """
                    DELETE FROM svi_tracts WHERE source_snapshot_id IN (
                        SELECT id FROM source_snapshots WHERE evidence_mode = 'DEMO_FIXTURE'
                    )
                    """
                )
            )
            await session.execute(
                text("DELETE FROM source_snapshots WHERE evidence_mode = 'DEMO_FIXTURE'")
            )

        stops_snapshot = await snapshots.record_snapshot(
            session,
            source_name=snapshots.PHOENIX_SOURCE_NAME,
            source_url=str(BUS_STOPS_FIXTURE.as_posix()),
            source_version="demo-fixture-v1 (synthetic, not a City of Phoenix extract)",
            checksum=stops_checksum,
            evidence_mode=RuntimeMode.DEMO_FIXTURE.value,
            license_note=FIXTURE_LICENSE_NOTE,
        )
        svi_snapshot = await snapshots.record_snapshot(
            session,
            source_name=snapshots.SVI_SOURCE_NAME,
            source_url=str(SVI_FIXTURE.as_posix()),
            source_version="demo-fixture-v1 (synthetic, 2022 SVI field shape only)",
            checksum=tracts_checksum,
            evidence_mode=RuntimeMode.DEMO_FIXTURE.value,
            license_note=FIXTURE_LICENSE_NOTE,
        )

        stop_rows = []
        for feature in stops_doc["features"]:
            props = feature["properties"]
            lon, lat = feature["geometry"]["coordinates"]
            stop_rows.append(
                {
                    "stop_id": props["STOP_ID"],
                    "location_name": props["LOCATION_NAME"],
                    "shelter_count": int(props["NBR_SHELTERS"]),
                    "ridership_value": float(props["RIDERSHIP"]),
                    "longitude": float(lon),
                    "latitude": float(lat),
                    "snapshot_id": str(stops_snapshot.id),
                }
            )
        await session.execute(_UPSERT_STOP, stop_rows)

        tract_rows = []
        for feature in tracts_doc["features"]:
            props = feature["properties"]
            tract_rows.append(
                {
                    "geoid": props["GEOID"],
                    "overall_percentile": float(props["RPL_THEMES"]),
                    "geometry": json.dumps(feature["geometry"]),
                    "snapshot_id": str(svi_snapshot.id),
                }
            )
        await session.execute(_UPSERT_TRACT, tract_rows)

        print(f"bus_stops upserted : {len(stop_rows)}")
        print(f"svi_tracts upserted: {len(tract_rows)}")
        print(f"stops snapshot     : {stops_snapshot.id}")
        print(f"svi snapshot       : {svi_snapshot.id}")

    await dispose_engine()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--reset",
        action="store_true",
        help="Delete existing DEMO_FIXTURE rows first. Live records are never touched.",
    )
    args = parser.parse_args()
    asyncio.run(load(args.reset))


if __name__ == "__main__":
    main()
